package:
    name:           hipanel-module-request
    namespace:      hipanel\modules\request
    label:          HiPanel RequestModule
    title:          Request Plugin for HiPanel
    type:           yii2-extension
    keywords:       request, hipanel, plugin
    year:           2014

require:
    hiqdev/hidev-config-php:    "*@dev"
